CSVImport/Controllers/ImportController.cs
using CSVImport.DAL;
using CSVImport.DAL.edmx;
using CSVImport.DAL.Models;
using System;
using System.Collections.Generic;
using System.Globalization;
using System.IO;
using System.Linq;
using System.Threading;
using System.Web;
using System.Web.Mvc;

namespace CSVImport.Controllers
{
    public class ImportController : Controller
    {
        private IImportRepository importRepository;

        public ImportController()
        {
            this.importRepository = new ImportRepository(new ImportsContext());
        }

        public ImportController(IImportRepository importRepository)
        {
            this.importRepository = importRepository;
        }

        [HttpGet]
        public ActionResult ImportFile()
        {
            return View();
        }

        // GET: Import
        [HttpPost]
        public ActionResult ImportFile(HttpPostedFileBase postedFile)
        {
            try
            {
                string filePath = string.Empty;
                if (postedFile != null)
                {
                    string path = Server.MapPath("~/Uploads/");
                    if (!Directory.Exists(path))
                    {
                        Directory.CreateDirectory(path);
                    }
                    filePath = path + Path.GetFileName(postedFile.FileName);
                    string extension = Path.GetExtension(postedFile.FileName);
                    if (!extension.ToLower().Contains("csv"))
                    {
                        ViewBag.Result = "Invalid file format...allowed format is .csv";
                        return View();
                    }

                    postedFile.SaveAs(filePath);

                    //Read the contents of CSV file.
                    string csvData = System.IO.File.ReadAllText(filePath);

                    
                    foreach (string row in csvData.Split('\n').Skip(1))
                    {
                        if (!string.IsNullOrEmpty(row))
                        {
                            var context = new ImportsContext();
                            using (var transaction = context.Database.BeginTransaction())
                            {
                                try
                                {
                                    string TransDate = row.Split(',')[5];
                                    string EffectiveDate = row.Split(',')[8].Replace("\r", "");
                                    importRepository.InsertImport(new ImportData
                                    {
                                        ID = Guid.NewGuid(),
                                        PaymentID = int.Parse(row.Split(',')[0]),
                                        AccountHolder = row.Split(',')[1],
                                        BranchCode = int.Parse(row.Split(',')[2]),
                                        AccountNumber = (long)Convert.ToDouble(row.Split(',')[3]),
                                        AccountType = int.Parse(row.Split(',')[4]),
                                        TransactionDate = DateTime.ParseExact(TransDate, "dd/MM/yyyy", CultureInfo.InvariantCulture),
                                        Amount = Convert.ToDecimal(row.Split(',')[6]),
                                        Status = int.Parse(row.Split(',')[7]),
                                        EffectiveStatusDate = DateTime.ParseExact(EffectiveDate, "dd/MM/yyyy", CultureInfo.InvariantCulture)
                                    });
                                    importRepository.Save();
                                    Thread.Sleep(1000);
                                    transaction.Commit();
                                }
                                catch (Exception ex)
                                {
                                    ViewBag.Result = "ERROR: " + ex.Message;
                                    transaction.Rollback();
                                }
                            }
                        }
                    }
                    ViewBag.Result = "Import completed successfully.";
                }
            }
            catch(Exception ex) 
            {
                ViewBag.Result = "ERROR: " + ex.Message;
                return View(); 
            }
            return View();
        }

        [HttpGet]
        public ActionResult ImportView(string AccountNumber = "")
        {
            try
            {
                bool valid = false;
                string partialViewHtml = string.Empty;
                ImportMasterDetailViewModel importView = new ImportMasterDetailViewModel 
                { 
                    ImportMasters = importRepository.GetImportMasters().ToList() 
                };

                if (!string.IsNullOrEmpty(AccountNumber))
                {
                    ImportMasterDetailViewModel masterDetails = new ImportMasterDetailViewModel
                    {
                        ImportMasterDetails = importRepository.GetImportMasterDetails((long)Convert.ToDouble(AccountNumber)).ToList()
                    };
                    importView.AccountNumber = AccountNumber;
                    importView.ImportMasterDetails = masterDetails.ImportMasterDetails;
                }
                if (Request.IsAjaxRequest())
                {
                    valid = true;
                    partialViewHtml = RenderPartialViewToString("_ImportMasterDetailsGrid", importView);
                    return Json(new
                    {
                        Valid = valid,
                        Errors = GetErrorsFromModelState(),
                        PartialView = partialViewHtml
                    }, JsonRequestBehavior.AllowGet);
                }
                else
                {
                    return View(importView);
                }
            }
            catch
            {
                return View();
            }
        }

        [HttpGet]
        public ActionResult Report()
        {
            try
            {
                IEnumerable<ReportModel> report = importRepository.GetImportsReport();
                return View(report);
            }
            catch
            {
                return View();
            }
        }

        [HttpGet]
        public ActionResult EditMaster(string AccountNumber)
        {
            try
            {
                ImportData importData = BuildMasterView(AccountNumber);
                return View(importData);
            }
            catch
            {
                return View();
            }
        }

        private ImportData BuildMasterView(string AccountNumber)
        {
            //Account Type list
            List<SelectListItem> AccTypeList = new List<SelectListItem>()
                {
                    new SelectListItem { Text = "Cheque", Value = "1" },
                    new SelectListItem { Text = "Savings", Value = "2" }
                };

            //Assigning generic list to ViewBag
            ViewBag.AccountTypes = AccTypeList;
            ImportData importData = importRepository.GetImportMaster((long)Convert.ToDouble(AccountNumber));
            return importData;
        }

        [HttpPost]
        public ActionResult EditMaster(ImportData ModelData)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    if (ModelData.AccountNumber > 0 && ModelData.AccountType > 0)
                    {
                        importRepository.UpdateImport(ModelData);
                        ViewBag.Result = "Record Updated Successfully.";
                    }
                }
            }
            catch
            {

            }
            ImportData importData = BuildMasterView(ModelData.AccountNumber.ToString());
            return View(importData);
        }

        virtual public string RenderPartialViewToString(string viewName, object model)
        {
            ViewData.Model = model;
            using (var sw = new StringWriter())
            {
                var viewResult = ViewEngines.Engines.FindPartialView(ControllerContext, viewName);
                var viewContext = new ViewContext(ControllerContext, viewResult.View, ViewData, TempData, sw);
                viewResult.View.Render(viewContext, sw);

                return sw.GetStringBuilder().ToString();
            }
        }

        virtual public Dictionary<string, object> GetErrorsFromModelState()
        {
            var errors = new Dictionary<string, object>();
            foreach (var key in ModelState.Keys)
            {
                // Only send the errors to the client.
                if (ModelState[key].Errors.Count > 0)
                {
                    errors[key] = ModelState[key].Errors;
                }
            }

            return errors;
        }
    }
}

CSVImport/Views/Import/EditMaster.cshtml
@using CSVImport.DAL.edmx;
@model ImportData

@{
    ViewBag.Title = "EditMaster";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
@using (Html.BeginForm("EditMaster", "Import", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    <div class="panel panel-default">
        <div class="panel-heading">
            <h4 class="panel-title">
                <a data-toggle="collapse" data-parent="#accordion" href="#collapsefour">
                    <b>Edit Master Record</b>
                </a>
            </h4>
        </div>
        <div class="panel-body">
            <div class="row">
                <div class="col-sm-2">
                    Account Holder:
                </div>
                <div class="col-sm-2">
                    @Html.HiddenFor(model => model.AccountNumber)
                    @Html.DisplayFor(model => model.AccountHolder)
                </div>
            </div>
            <div class="row">
                <div class="col-sm-2">
                    Branch Code:
                </div>
                <div class="col-sm-10">
                    @Html.DisplayFor(model => model.BranchCode)
                </div>
            </div>
            <div class="row">
                <div class="col-sm-2">
                    Account Number:
                </div>
                <div class="col-sm-10">
                    @Html.DisplayFor(model => model.AccountNumber)
                </div>
            </div>
            <div class="row">
                <div class="col-sm-2">
                    Account Type:
                </div>
                <div class="col-sm-10">

                </div>
            </div>
            <div class="row">
                <div class="col-sm-2">
                </div>
                <div class="col-sm-10">
                    @Html.DropDownListFor(model => model.AccountType, new SelectList((IEnumerable<SelectListItem>)ViewBag.AccountTypes, "Value", "Text"), new { id = "ddlAccountTypes", @class = "form-control" })
                </div>
            </div>            
        </div>
        <div class="panel-footer">
            <div class="row">
                <div class="col-sm-2">
                </div>
                <div class="col-sm-10">
                    <input type="submit" name="submitButton" value="Save" class="btn btn-info" />
                    @Html.ActionLink("Close", "ImportView", "Import", null, new { @class = "btn btn-danger btn-large" })
                </div>
            </div>
        </div>
    </div>
}
@if (ViewBag.Result != null)
{
    <script>
        jQuery(function ($) {
            alertify.alert('@ViewBag.Result');
        });
    </script>
}

CSVImport/Views/Import/ImportFile.cshtml
@{
    ViewBag.Title = "ImportFile";
    Layout = "~/Views/Shared/_Layout.cshtml";

    <script type="text/javascript">
        jQuery(function () {
            $("#btnUpload").click(function (e)
            {
                var fileName = $("#postedFile").val();

                if (fileName) {
                    return true;
                }
                else {
                    alertify.alert("Please select a file");
                    return false;
                }
            });
        });
    </script>
}

<h4>Import Uploader</h4>

@using (Html.BeginForm("ImportFile", "Import", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    <div class="row">
        <div class="col-sm-6">
            <input type="file" id="postedFile" name="postedFile" class="form-control" />
        </div>
    </div>
    <div class="row">
        <div class="col-sm-6">
            <input type="submit" id="btnUpload" value="Upload" class="btn btn-success" />
        </div>
    </div>
}

@if (ViewBag.Result != null)
{
    <script>
        jQuery(function ($) {
            alertify.alert('@ViewBag.Result');
        });
    </script>
}

CSVImport/Views/Import/ImportView.cshtml
@using CSVImport.DAL.Models;
@model ImportMasterDetailViewModel
@{
    ViewBag.Title = "Report";
    Layout = "~/Views/Shared/_Layout.cshtml";
    <script type="text/javascript">
        jQuery(function ($) {
            $(".anchorDetail").click(function () {
                var $buttonClicked = $(this);
                var accountNumber = $buttonClicked.attr('data-AccountNumber');

                var MasterDetailsUrl = '@Url.Action("ImportView")';

                $.ajax({
                    type: "GET",
                    url: MasterDetailsUrl,
                    data: { AccountNumber: accountNumber },
                    contentType: "application/json; charset=utf-8",
                    datatype: "json",
                    success: function (data) {                        
                        if (data.Valid) {
                            $("div#result").html(data.PartialView);
                        }
                    },
                    error: function (xhr) {
                        alert(xhr.responseText);
                    }
                });
            });
        });
    </script>
}

<h2>Master Grid</h2>
@(Html
    .Grid(Model.ImportMasters)
    .Build(columns =>
    {
        columns.Add().Encoded(false).RenderedAs(c => @Html.ActionLink("Edit", "EditMaster", new { AccountNumber = c.AccountNumber }));
        columns.Add(model => model.AccountHolder).Titled("Account Holder");
        columns.Add(model => model.BranchCode).Titled("Branch Code");
        columns.Add(c => c.AccountNumber).Titled("Account Number").Encoded(false).RenderedAs(o => new HtmlString
        (
            "<a href='javascript:void(0);' class='anchorDetail' data-AccountNumber='" + o.AccountNumber + "'>" + o.AccountNumber + "</a>"
        ));
        columns.Add(model => model.AccountType).Titled("Account Type");
    }).Filterable().Sortable()
    .Empty("No data found")
    .Filterable()
)

<div class="row">
    <div class="col-sm-12">
        <hr />
        <br />
        <div id="result">
        </div>
    </div>
</div>

CSVImport/Views/Import/Report.cshtml
@using CSVImport.DAL.Models;
@model IEnumerable<ReportModel>
@{
    ViewBag.Title = "Report";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Import Report</h2>
@(Html
    .Grid(Model)
    .Build(columns =>
    {
        columns.Add(model => model.BranchCode).Titled("Branch Code");
        columns.Add(model => model.AccountType).Titled("Account Type");
        columns.Add(model => model.Status).Titled("Status");
        columns.Add(model => model.TotalCount).Titled("TotalCount");
        columns.Add(model => model.TotalAmount).Titled("Total Amount");
    }).Filterable().Sortable()
    .Empty("No data found")
    .Filterable()
)

CSVImport/Views/Import/_ImportMasterDetailsGrid.cshtml
@using CSVImport.DAL.Models;
@model ImportMasterDetailViewModel
@{

    <style type="text/css">
        .Yellow {
            color: yellow;
        }

        .Green {
            color: green;
        }

        .Blue {
            color: blue;
        }
        .Normal
        {
            font-weight: normal;
        }
    </style>
}
<h4>Detail Grid - @Model.AccountNumber</h4>
@(Html
    .Grid(Model.ImportMasterDetails)
    .Build(columns =>
    {
        columns.Add(model => model.TransactionDate).Titled("Transaction Date").Formatted("{0:yyyy-MM-dd}");
        columns.Add(model => model.Amount).Encoded(true).Titled("Amount").RenderedAs(o => CustomRenderingOfColumn(o, true));
        columns.Add(model => model.Status).Titled("Status");
        columns.Add(model => model.EffectiveStatusDate).Titled("Effective Status Date").Formatted("{0:yyyy-MM-dd}");
        columns.Add(model => model.TimeBreached).Encoded(true).Titled("TimeBreached").RenderedAs(o => CustomRenderingOfColumn(o, false));
    }).Filterable().Sortable()
    .Empty("No data found")
    .Filterable()
)

@helper CustomRenderingOfColumn(ImportMasterDetailModel customer, bool flag)
{
    if (!flag)
    {
        if (((DateTime)customer.EffectiveStatusDate - (DateTime)customer.TransactionDate).TotalDays >= 7)
        {
            <label class="Yellow">Yes</label>
        }
        else
        {
            <label class="Green">No</label>
        }
    }
    else
    {
        if (customer.Amount > 500)
        {
            <label class="Blue">@customer.Amount</label>
        }
        else
        {
            <label class="Normal">@customer.Amount</label>
        }
    }
}